import {
  Aperture,
  Apple,
  Atom,
  Backpack,
  Bike,
  BookOpenText,
  Brain,
  Briefcase,
  Brush,
  Camera,
  Car,
  Cat,
  CircleDollarSign,
  ClipboardPenLine,
  Code,
  Dog,
  Drill,
  Drum,
  Dumbbell,
  FlaskConical,
  GraduationCap,
  Guitar,
  Hammer,
  Keyboard,
  Medal,
  Mic,
  Monitor,
  Music,
  NotebookPen,
  Piano,
  Shirt,
  Stethoscope,
  Store,
  Tablets,
  Wrench,
  Calendar,
  Check,
  Clock,
  Tag,
  User,
  Users,
  Settings,
  Trash2,
  Plus,
  Minus,
  Search,
  Send,
  Bell,
  Bookmark,
  Heart,
  Star,
  Folder,
  Paperclip,
  Link,
  Globe,
  MapPin,
  Phone,
  Mail,
  Edit,
  RefreshCw,
} from "lucide-react";

export const Icons = {
  work: <Briefcase className="w-5 h-5" />,
  dumbbell: <Dumbbell className="w-5 h-5" />,
  graduation: <GraduationCap className="w-5 h-5" />,
  bookOpen: <BookOpenText className="w-5 h-5" />,
  notebook: <NotebookPen className="w-5 h-5" />,
  code: <Code className="w-5 h-5" />,
  car: <Car className="w-5 h-5" />,
  apple: <Apple className="w-5 h-5" />,
  drill: <Drill className="w-5 h-5" />,
  aperture: <Aperture className="w-5 h-5" />,
  atom: <Atom className="w-5 h-5" />,
  bike: <Bike className="w-5 h-5" />,
  brush: <Brush className="w-5 h-5" />,
  brain: <Brain className="w-5 h-5" />,
  cat: <Cat className="w-5 h-5" />,
  camera: <Camera className="w-5 h-5" />,
  dollar: <CircleDollarSign className="w-5 h-5" />,
  clipboard: <ClipboardPenLine className="w-5 h-5" />,
  flask: <FlaskConical className="w-5 h-5" />,
  monitor: <Monitor className="w-5 h-5" />,
  shirt: <Shirt className="w-5 h-5" />,
  music: <Music className="w-5 h-5" />,
  guitar: <Guitar className="w-5 h-5" />,
  piano: <Piano className="w-5 h-5" />,
  drum: <Drum className="w-5 h-5" />,
  mic: <Mic className="w-5 h-5" />,
  backpack: <Backpack className="w-5 h-5" />,
  dog: <Dog className="w-5 h-5" />,
  keyboard: <Keyboard className="w-5 h-5" />,
  hammer: <Hammer className="w-5 h-5" />,
  medal: <Medal className="w-5 h-5" />,
  wrench: <Wrench className="w-5 h-5" />,
  tablets: <Tablets className="w-5 h-5" />,
  stethoscope: <Stethoscope className="w-5 h-5" />,
  store: <Store className="w-5 h-5" />,
  calendar: <Calendar className="w-5 h-5" />,
  check: <Check className="w-5 h-5" />,
  clock: <Clock className="w-5 h-5" />,
  tag: <Tag className="w-5 h-5" />,
  user: <User className="w-5 h-5" />,
  users: <Users className="w-5 h-5" />,
  settings: <Settings className="w-5 h-5" />,
  trash: <Trash2 className="w-5 h-5" />,
  plus: <Plus className="w-5 h-5" />,
  minus: <Minus className="w-5 h-5" />,
  search: <Search className="w-5 h-5" />,
  send: <Send className="w-5 h-5" />,
  bell: <Bell className="w-5 h-5" />,
  bookmark: <Bookmark className="w-5 h-5" />,
  heart: <Heart className="w-5 h-5" />,
  star: <Star className="w-5 h-5" />,
  folder: <Folder className="w-5 h-5" />,
  paperclip: <Paperclip className="w-5 h-5" />,
  link: <Link className="w-5 h-5" />,
  globe: <Globe className="w-5 h-5" />,
  pin: <MapPin className="w-5 h-5" />,
  phone: <Phone className="w-5 h-5" />,
  mail: <Mail className="w-5 h-5" />,
  edit: <Edit className="w-5 h-5" />,
  refresh: <RefreshCw className="w-5 h-5" />,
};
