import {
  Aperture,
  Apple,
  Atom,
  Backpack,
  Bike,
  BookOpenText,
  Brain,
  Briefcase,
  Brush,
  Camera,
  Car,
  Cat,
  CircleDollarSign,
  ClipboardPenLine,
  Code,
  Dog,
  Drill,
  Drum,
  Dumbbell,
  FlaskConical,
  GraduationCap,
  Guitar,
  Hammer,
  Keyboard,
  Medal,
  Mic,
  Monitor,
  Music,
  NotebookPen,
  Piano,
  Shirt,
  Stethoscope,
  Store,
  Tablets,
  Wrench,
} from "lucide-react";

export const Icons = {
  work: <Briefcase className="w-5 h-5" />,
  dumbbell: <Dumbbell className="w-5 h-5" />,
  graduation: <GraduationCap className="w-5 h-5" />,
  bookOpen: <BookOpenText className="w-5 h-5" />,
  notebook: <NotebookPen className="w-5 h-5" />,
  code: <Code className="w-5 h-5" />,
  car: <Car className="w-5 h-5" />,
  apple: <Apple className="w-5 h-5" />,
  drill: <Drill className="w-5 h-5" />,
  aperture: <Aperture className="w-5 h-5" />,
  atom: <Atom className="w-5 h-5" />,
  bike: <Bike className="w-5 h-5" />,
  brush: <Brush className="w-5 h-5" />,
  brain: <Brain className="w-5 h-5" />,
  cat: <Cat className="w-5 h-5" />,
  camera: <Camera className="w-5 h-5" />,
  dollar: <CircleDollarSign className="w-5 h-5" />,
  clipboard: <ClipboardPenLine className="w-5 h-5" />,
  flask: <FlaskConical className="w-5 h-5" />,
  monitor: <Monitor className="w-5 h-5" />,
  shirt: <Shirt className="w-5 h-5" />,
  music: <Music className="w-5 h-5" />,
  guitar: <Guitar className="w-5 h-5" />,
  piano: <Piano className="w-5 h-5" />,
  drum: <Drum className="w-5 h-5" />,
  mic: <Mic className="w-5 h-5" />,
  backpack: <Backpack className="w-5 h-5" />,
  dog: <Dog className="w-5 h-5" />,
  keyboard: <Keyboard className="w-5 h-5" />,
  hammer: <Hammer className="w-5 h-5" />,
  medal: <Medal className="w-5 h-5" />,
  wrench: <Wrench className="w-5 h-5" />,
  tablets: <Tablets className="w-5 h-5" />,
  stethoscope: <Stethoscope className="w-5 h-5" />,
  store: <Store className="w-5 h-5" />,
};
